apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mikedutuandu-com-tls
spec:
  secretName: mikedutuandu-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mikedutuandu.com
  dnsNames:
    - mikedutuandu.com
    - www.mikedutuandu.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - mikedutuandu.com
          - www.mikedutuandu.com